#!/usr/bin/env bash

function docker_handle_request() {
  local docker_image_id docker_ports public_port docker_image_created response
  docker_repository="$1"
  docker_version="$2"
  docker_internal_port="$3"
  request="$(cat)"

  docker_id="$(curl -s "http://localhost:8080/running/${docker_repository}/${docker_version}")"
  if [[ -z "$docker_id" ]];then
    log "docker: launch new container from repository: ${docker_repository}"
    docker_id="$(curl -s "http://localhost:8080/launch/${docker_repository}/${docker_version}")"
  fi
  if [[ -z "$docker_id" ]];then
    log "docker: ${docker_repository} could not launch container"
    exit 1
  fi
  docker_port="$(curl -s "http://localhost:8080/publicport/${docker_id}/${docker_internal_port}")"
  if [[ -z "$docker_port" ]];then
    log "docker: ${docker_repository} could not find public port"
    exit 1
  fi
  for i in {1..10}; do 
    log "docker_request: ${docker_id} ${docker_repository} localhost:${public_port}${docker_request_uri}"
    response="$( \
      echo -e "${request}\n" | socat -t 10 - TCP:localhost:${docker_port},shut-none \
    )"
    if [[ -n "$response" ]];then
      break
    fi
    log "docker: [${docker_id}] response was empty retry in 0.1 seconds"
    sleep 0.2
  done
  log "docker_response: [${docker_id}] $(sed -n '1p' <<<"$response")"
  sed -n '1p' <<<"${response}"
  echo "Docker_Image_Name: ${docker_id}"
  echo "Custon_Header: injected"
  sed -n '2,$p' <<<"${response}"
}

