#!/usr/bin/env bash

function log() {
  if [[ -n "$LOG_FILE" ]];then
    echo "$(date +%FT%T.%3N) $(date +%s%3N) $$ $@" >>${LOG_FILE}
  else
    echo "$(date +%FT%T.%3N) $(date +%s%3N) $$ $@" >&2
  fi
}

# TODO check existence of log file, and create directory

