#!/usr/bin/env bash

function main() {
  parse_request

  log "request: ${SOCAT_PEERADDR}:${SOCAT_PEERPORT} ${request_method} ${request_uri}"

  read \
    docker_repository \
    docker_version \
    docker_request_uri \
    docker_port \
    < <(extract_docker_information_from_path "$request_uri")

  if [[ "$docker_repository" = "-" ]];then
    log "request: internal ${request_method} ${request_uri}"
    echo -e "${request_method} ${docker_request_uri} ${request_http_version}\n${request_header_lines}${request_content}" \
      | socat -t 10 - TCP:localhost:8080,shut-none

  elif [[ -n "$docker_repository" ]];then
    response="$( 
    echo -e "${request_method} ${docker_request_uri} ${request_http_version}\n${request_header_lines}${request_content}" \
      | docker_handle_request "$docker_repository" "$docker_version" "$docker_port" )"
    docker_return_code="$?"
    if [[ -n "$response" ]];then
      echo "$response"
      exit 0
    else
      log "docker_error: return code: $docker_return_code"
      echo_response_status_line 500 "Internal Server Error"
    fi
  else
    echo_response_status_line 404 "Not Found"
  fi
}

